/* Created by Shelley Witte, 2016 */

$('#mydiv').html('Hello World!');

function initialize() {
    // initializes functions that are defined below
    cities();
    addColumns();
    addEvents();
    jQueryAjax();

};

//createsglobal variable cityPop
var cityPop;

//creates cities function which contains cityPop array with city objects
function cities() {
    //cityPop array which has cities with two properties: city and population
    cityPop = [
    {
        city: 'Minneapolis',
        population: 400070
    },
    {
        city: 'St. Paul',
        population: 294873,
    },
    {
        city: 'Washington, DC',
        population: 658893
    },
    {
        city: 'Stillwater',
        population: 18674
    }
    ];

    //appends a table to the div
    $("#mydiv").append("<table>");

    //appends a header row to the table (located in the div)
    $("table").append("<tr>");

    //adds "City" and "Population" columns to the header row (in the table)
    $("tr").append("<th>City</th><th>Population</th>");

    //loop to add a new row for each city
    for (var i = 0; i < cityPop.length; i++){
        //assign longer html strings to a variable
        var rowHtml = "<tr><td>" + cityPop[i].city + "</td><td>" + cityPop[i].population + "</td></tr>";
        //add the row's html string to the table
        $("table").append(rowHtml);
    };
};


//Debugging section #1

// defines a function that takes the cityPop global variable as a parameter 
function addColumns(){
    
    // iterates over each row in the table 
    $('tr').each(function(i){

        if (i == 0){

            // adds (appends) a third column to the table with the header labeled "City Size"
            $(this).append('<th>City Size</th>');
        } else {

            //creates variable citySize 
            var citySize;
            
            //if statement that looks at cityPop object population property and
            //designates the city as small/medium/large according to the criteria
            if (cityPop[i-1].population < 100000){
                citySize = 'Small';

            } else if (cityPop[i-1].population < 500000){
                citySize = 'Medium';

            } else {
                citySize = 'Large';
            };

            //adds the city size designation as new table data to the same row 
            //it assessed in the if statement
            $(this).append('<td>' + citySize + '</td>');
        };


    });
};


function addEvents(){

    //adds mouseover listener that will perform a function when the table is moused over
    $('table').mouseover(function(){
        
        //defines variable to set the text color using format: rgb(#,#,#)
        var color = "rgb(";

        //for loop that grabs 3 separate random numbers between 0 and 255 and puts them
        //together (concatenates them) into a string
        for (var i=0; i<3; i++){

            //generates a random number between 0 and 255 and assigns it to variable
            //named random
            var random = Math.round(Math.random() * 255);

            //takes random number generated by above process and adds it to string "rgb(
            color += random;

            //adds a comma to the "rgb(" string if less than three random numbers in string
            if (i<2) {
                color += ",";
            
            //adds a closed parenthesis to end of string to complete "rgb(#,#,#)""
            } else {
                color += ")";
        };
    }
        //uses css jquery method to change the text color to whatever random color the 
        //variable color is currently set to
        $(this).css('color', color);
        
    });
    
    // adds click listener that will give a pop-up alert if the table is clicked on
    $('table').click(function(){
        alert('Hey, you clicked me!');
    });

};

//an AJAX function
function jQueryAjax(){
    
    var mydata;

    $.ajax("data/MegaCities.geojson", {
        dataType: "json", 
        success: callback
    });

};

function callback(response) {
    console.log(response);
}

//calls initialize function to excute the functions within that function
$(document).ready(initialize);

// function debugCallback(response){
    
//     $(mydiv).append('GeoJSON data: ' + JSON.stringify(mydata));
// };

// function debugAjax(){
    
//     var mydata;

//     $.ajax("data/MegaCities.geojson", {
//         dataType: "json",
//         success: function(response){
            
//             debugCallback(mydata);
//         }
//     });

//     $(mydiv).append('<br>GeoJSON data:<br>' + JSON.stringify(mydata));
// };

// $(mydiv).append('GeoJSON data: ' + JSON.stringify(mydata));